### ISSUE TITLE
`ERROR collecting examples/lookahead_mnist_test.py`

### ISSUE THREAD

**Issue by samuela** [deepmind/optax#323]
I'm getting an error running the test suite, in particular in the `examples/` directory:
```
============================= test session starts ==============================
platform linux -- Python 3.9.10, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /build/source
collected 1585 items / 1 error / 1584 selected                                 

==================================== ERRORS ====================================
______________ ERROR collecting examples/lookahead_mnist_test.py _______________
examples/lookahead_mnist_test.py:31: in <module>
    flags.FLAGS(sys.argv)
/nix/store/dagbzxd9qccmjykhz1x0wayzadlc96rp-python3.9-absl-py-1.0.0/lib/python3.9/site-packages/absl/flags/_flagvalues.py:669: in __call__
    raise _exceptions.UnrecognizedFlagError(
E   absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'ignore'
```
I'm running via pytest on optax version 0.1.1.

**Comment by mkunesch** [comment]
Hi! Thanks for raising this!

 I'm actually tempted to just remove the flags from this example and make them hard-coded constants at the top of the file. The flags have also caused problems with the github test workflow in the past and since this is not production code and just an example I don't think anybody actually needs the flags. What do yo think?

**Comment by samuela** [comment]
Yeah, if there causing you problems then I think it makes sense to just remove 'em. I think that anyone reading the code ought to be able to figure out how to add config flags if they so desire. Removing them also helps keep the focus on optax itself. Just my 2c 🤷
