### ISSUE TITLE
Better tests for utils.

### ISSUE THREAD

**Issue by mkunesch** [deepmind/optax#404]
Optax tests did not catch a problem with one of the type annotations in #367. This is due to `utils` not having good test coverage. 

I'm marking this as "good first issue". Any tests for `utils` would be very welcome! No need to write tests for all of them at once, PRs with only a single test at a time are very welcome.

**Comment by adit299** [comment]
Hi, I am a new contributor to Optax, and I would love to try to tackle this issue. If no one else is assigned to this issue, I would love to be assigned to take a crack at it!

**Comment by mkunesch** [comment]
Hi! Sorry for the late reply - yes, that'd be great! Let me know if you have any questions or would like to discuss!

**Comment by adit299** [comment]
Hello mkunesch,

I had a look at utils.py and utils_test.py to try to write some unit tests for the sample function in particular. However, I am having a hard time as there doesn't seem to be much documentation about the utils.py file. Would you be open to having a call, so that we can discuss in more depth what the sample function is doing, and what would be the desired approach to write unit tests for the sample function. This is my Discord: krish299#9037.
If you have any other preferred forms of communications or suggestions for how to start with this task, I would appreciate it very much.
