### ISSUE TITLE
Tests don't run on Mac

### ISSUE THREAD

**Issue by heytanay** [deepmind/optax#450]
I have been trying to run the tests using `bash test.sh` on Mac (M1 Pro chip) but the script ends in an error. Below is the screenshot of the error encountered.

<img width="1005" alt="Screenshot 2022-11-05 at 10 40 07 AM" src="https://user-images.githubusercontent.com/26519539/200102346-f1b818a8-9362-496a-a68f-2ccccc27f0b5.png">

I then tried running the `grep -c ^processor /proc/cpuinfo` command as it looks like it is responsible for the error and the output is:

```shell
$ grep: /proc/cpuinfo: No such file or directory
```

Is there anything that I am doing wrong here?

Any help would be greatly appreciated because the other remaining option for running the tests is to use GitHub Codespaces which is not very convenient!

**Comment by rosshemsley** [comment]
Hey @heytanay , looks like this is because /proc/cpuinfo call is failing on your machine.

It appears that we could replace this with `auto` to get the same effect (this is used to set the number of CPUs to use when running the test), and the call above is trying to guess how many you have available.

I will look at getting a fix in, though you can try making the change directly and see if it helps!

**Comment by rosshemsley** [comment]
(reference in the docs: https://pypi.org/project/pytest-xdist/)
